### ISSUE TITLE
Using the model for multiple features

### ISSUE THREAD

**Issue by rfsilva1** [eren-ck/st_dbscan#5]
Hi there,

First, congrats for the great implementation of ST-DBSCAN. I'm evaluating using it for a research on spatiotemporal clustering of meteorological data (with multiple features).
However, I have a question on your implementation: 
- How should I organize the inputs to the model for multiple features for each data point? As far as I understood from the documentation, it should be: 
[[time_step1, data_point_ID, x, y, feature 1, feature 2, feature n],[time_step2, data_point_ID, x, y, feature 1, feature 2, feature n]]

An example of data point would be: on the first timestep, 300 is a specific city, x is latitude, y is longitude, feature 1 is precipitation, feature 2 is temperature, feature n is solar radiation:
[0, 300, -23.5505, -46.6333, 1271.001, 28.763, 17.971]

Thanks a lot!

Roberto

**Comment by eren-ck** [comment]
Hello Roberto, 
the input for the implementation should be `['time', 'x', 'y', 'feature_1', 'feature_2',...]`. Further, you should normalize all features features expect for the time. 

If you want to use `[lat, long]` values instead of `[x, y]` you have to convert the values from the sphere to the plane. So I propose transforming the sphere coordinates to the utm coordinate system and inputting the data into the st_dbscan. 

I hope that helps you. 

Cheers, 
Eren
